name = "SmallCombinatorics"
uuid = "4c2fb5cd-5fa8-4952-858b-935ef2e5e854"
version = "0.1.1"
authors = ["matthias314"]

[deps]
SmallCollections = "2b935e18-93d6-40ac-ae34-fe54c09f00e1"

[compat]
BitIntegers = "0.3"
SmallCollections = "0.5"
julia = "1.10"

[extras]
BitIntegers = "c3b6d118-76ef-56ca-8cc7-ebb389d030a1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "BitIntegers"]
